# -*- coding: utf-8 -*-
"""morse_code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15stSD2Q62oa3Jr8Om9c75xGYTAhsO8Pg
"""

message=input('Please Enter A Message to conver to morse_code :\n')
morse_code={ 'A':'.-', 'B':'-...',
                'C':'-.-.', 'D':'-..', 'E':'.',
                'F':'..-.', 'G':'--.', 'H':'....',
                'I':'..', 'J':'.---', 'K':'-.-',
                'L':'.-..', 'M':'--', 'N':'-.',
                'O':'---', 'P':'.--.', 'Q':'--.-',
                'R':'.-.', 'S':'...', 'T':'-',
                'U':'..-', 'V':'...-', 'W':'.--',
                'X':'-..-', 'Y':'-.--', 'Z':'--..',
                '1':'.----', '2':'..---', '3':'...--',
                '4':'....-', '5':'.....', '6':'-....',
                '7':'--...', '8':'---..', '9':'----.',
                '0':'-----', ', ':'--..--', '.':'.-.-.-',
                '?':'..--..', '/':'-..-.', '-':'-....-',
                '(':'-.--.', ')':'-.--.-'}
decode=''
message=message.upper()
for i in message:
    if i!=' ':
        decode+=morse_code[i]
    else:
        decode+=' '
print(decode)